#!/usr/bin/env bash

function excute_subdirs_shell_pro()
{
    sub_dirs=$1
    subpro=$2
    cur_dir=`pwd`
    #for d in `ls -S .`;do
    for d in ${sub_dirs};do
        if [ -d "$d" ];then
            if [ -L "$d" ];then
                echo "Escape link dir ${d} in: " ${cur_dir}
            else
                pushd "$PWD" 1>/dev/null
                cd $d
                    #echo "current dir: " `pwd`
                    if [ -f "./${subpro}" ] && [ -x "./${subpro}" ];then
                        ./${subpro}
                        sleep 1
                    fi
                popd 1>/dev/null
            fi
        fi
    done
}

cd `dirname $0`

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

#
# 程序的启动顺序有相关性，影响能否正常服务
#
subdirs="project-a"   
subpro="start.sh"
excute_subdirs_shell_pro "${subdirs}" ${subpro}

echo
echo -e ${GREEN}"FINISHED."${END}
