#!/usr/bin/env bash

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

function program_ctrl()
{
    pname=$1
    so=$2
    cmd=$3
    echo
    if [ "${cmd}" = "stop" ] ; then
        pcount=`ps -ef |grep ${USER}| grep "\<${pname}\>" |grep -v "grep"|wc -l`
        if [ `expr ${pcount}` -gt 0 ]; then
            ps -ef |grep ${USER}| grep "\<${pname}\> " | awk '{print "kill " $2}'| bash
            echo -e ${RED}"\tkill ${pname}..."${END}
        else
            echo -e ${YELLOW}"\t${pname} 没有运行"${END}
        fi
    elif [ "${cmd}" = "start" ]; then
        if [ ! -d "../log" ];then
            mkdir ../log
        fi  
        echo -e "${GREEN}starting...${END}"
        pcount=`ps -ef |grep ${USER}| grep "\<${pname}\>" |grep -v "grep"|wc -l`
        if [ `expr ${pcount}` -gt 0 ]; then
            echo -e "${YELLOW}有 ${LIGHT_RED}${pname} ${YELLOW}正在运行中，请检查。${END}\n"
        else
            ./${pname} ../etc/bench.conf ./${so}
        fi
    elif [ "${cmd}" = "stat" ]; then
        pcount=`ps -ef |grep ${USER}| grep "\<${pname}\>" |grep -v "grep"|wc -l`
        ps -ef |grep ${USER}| grep "\<${pname}\>" |grep -v "grep"
        echo -e "\t${YELLOW}${pname}${GREEN} 进程数: ${LIGHT_RED}${pcount}${END}"
    elif [ "${cmd}" = "--help" ] || [ "$cmd" = "-h" ]; then
        echo -e "Usage:\n\t${LIGHT_GREEN}daemon.sh ${YELLOW}start|stop|restart|stat${END}"
    else
        echo -e "Usage:\n\t${LIGHT_GREEN}daemon.sh ${YELLOW}start|stop|restart|stat${END}"
    fi
}


#更换程序只需要更换下面两个值
pname="project_app"
the_so="libapp.so"

cd `dirname $0`
the_cmd=$1

program_ctrl ${pname} ${the_so} ${the_cmd}
